name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm install mocha

      # Install Chrome (this is needed for the tests)
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Install ChromeDriver (needed for Selenium to control Chrome)
      - name: Set up ChromeDriver
        uses: actions/setup-chromedriver@v1

      # Run your Selenium-based tests using Mocha
      - name: Run tests
        run: npm test

      # Debugging step to check Chrome and ChromeDriver versions
      - name: Check Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version
